var GAME_LEVELS = [
  ["x   x                                                    x!!!!!!x                                            x",
   "x   x                                                    xx!!!!xx                                            x",
   "x   x                                                    xxx!!xxx                                            x",
   "x   x                          oooooo    o   o              !!              oooooooo         o    o          x",
   "x   x                          xxxxxx    x   x              |               xxxxxxxx         x    x    xxx o x",
   "x   x                                                        |                                           x   x",
   "x   x                                           o                        o                               x o x",
   "x @ x                                           x                        x            x!!!x              x   x",
   "x o x                                                                                 xxxxx              x o x",
   "x   x                                              o                  o                                  x   x",
   "x o x                                              x                  x                                  x o x",
   "x   x                                                                                                    x   x",
   "x o x                                                                                                    x o x",
   "x   x                                                 xxxxx  | xxxxx                                     x   x",
   "x o x                                                       |                                            x o x",
   "x   x                                                       !!                                           xxxxx",
   "x o x                                                       !!                      o  o  o  o  o  o  o       ",
   "x   x                               xxxxx     xxxxx     x!!!!!!!!x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "x o x                o                                  xxxxxxxxxx                                            ",
   "x   x            o       o                                                                                    ",
   "x o          xxxx         xxxxx                                                                               ",
   "x             oox                                                                             xxxxx           ",
   "x             oox                                                                                   ooo       ",
   "xxxxxxxxxx  xxxxx   xxxxx     xxxxx     xxxxx     xxxxx     xxxxxxxxx xxx xxx xxx xxx xxx xxx       xxx       ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!|!!!|!!!|!!!|!!!|!!!|!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyxxxxxxxxx |        |              ",
   "          ooooo                                         xxxxxxxxxxyyxxxxxxxxxxxxxxxxxxxxx |                       ",
   "        xxxxxxxxxx     ooooo                                               xxxxxxxxxxxxxx               xxxx ooooo",
   "       xxxxxxyxxxxxxxxxxxxxxxxxxxxx   ooooo                                             x        o  xxxxxxxxxooooo",
   "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     ooooo                             x       xxx xxxxxxxxxxxxyx",
   "| o |xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        o    o   o    x      xxxx xxxxxxyxxxxxxx",
   "!!x!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      x     xxxxxxxxxxxxxxxxxxxx",
   "!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo                     x                         ",
   "!!!!!xxxxxxxxxyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo                        o   o   o    x| |      o    o    o     ",
   "x!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo                                       xxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxx      ",
   "!!!!xxxxyxxxxxxxxx                                                                                                ",
   "!!!!!xxxxxxxxxxxxx           o                                                              o     o    o    o     ",
   "!!!!!!                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!   o     o                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyxxxxxxxxxxxx!xxxxxxxxxxxxxxxxyxxxxxx",
   "!!!!!!!!!  x     x                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxx!x!x!xxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxo                                      xxxxyxxxxxxxxxxx!xxxxxxxxxxxxxxyxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxo                                     x xxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxo                                xxxxxxxxxxxxxxx",
   "!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxo                            xxx",
   "!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxo   xxx",
   "!!!!!!!!!xxxxxxxyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                             xxx",
   "!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyxxxxxxxxxxxxxxxxxx                                oxxxxxxxxxxxxxxx",
   "x!!x!!x!!xxxxxxxxxxxxxxxxxxxxxxyxxxxxxxxxxxxxxxxxxx                                     ox xxxxxxxx!!!!!!!!!!!!!!!",
   "x||x||x||x  x  x                                                      o   xxxxxxxxxxxxxxxx xxxxxxxxxxxxxxx!!!!!!!!",
   "                                                       o   xxxxxxxxxxxx!!!!!!xxxxxxxxyxxx! !xxxxxxxxxxxxxxxxxx!!!!",
   "         o     @                        o   xxxxxyxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxx!! !!xxxxxyxxxxxxxxxxxxx!!",
   "         x    xx             xxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxyxxxxxxxxxxxxxxxxxxx!|!xxxxxxyxxxxxxxxxxxxxx!",
   "!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx|xxxxxxxxxxxxxxxxxxxxxx!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
